# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - l-j1
      - l-j2
      - l-j3
      - l-j4
      - l-j5
      - l-j6
      - l-j7
  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - r-j1
      - r-j2
      - r-j3
      - r-j4
      - r-j5
      - r-j6
      - r-j7